name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # перечислите здесь каталоги ваших микросервисов
    strategy:
      matrix:
        module: [ User_Service ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build
        working-directory: ${{ matrix.module }}
        run: mvn -B -DskipTests package

      - name: Test
        working-directory: ${{ matrix.module }}
        run: mvn -B test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests (${{ matrix.module }})
          path: ${{ matrix.module }}/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

