spring:
  application:
    name: TwittService

  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINT}
    port: ${CASSANDRA_PORT}
    keyspace-name: ${CASSANDRA_KEY_SPACE}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER}
    schema-action: create_if_not_exists

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    user-topic: ${KAFKA_USER_TOPIC}
    index-topic: ${KAFKA_INDEX_TOPIC}
    twitt-interaction-topic: ${KAFKA_TWITT_INTERACTION}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

configs:
  redis:
    randomly-recommended-days: ${CONFIGURATION_REDIS_RANDOMLY_RECOMMENDED_TIME}
    trend-recommended-days: ${CONFIGURATION_REDIS_TREND_TIME}
    trend-twitt-prefix: ${CONFIGURATION_REDIS_TREND_PREFIX}
    trend-key-set-prefix: ${CONFIGURATION_REDIS_TREND_LIST_PREFIX}
    random-key-set-prefix: ${CONFIGURATION_REDIS_RANDOM_LIST_PREFIX}
  local:
    trend_size: ${TWITT_SERVICE_TREND_SIZE}

server:
  port: 8002

grpc:
  server:
    port: 8003